// <auto-generated />
using System;
using System.Collections.Generic;
using GFlow.Infrastructure.Persistance;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GFlow.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260126150447_MakeMatchPlayerAwayNullable")]
    partial class MakeMatchPlayerAwayNullable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GFlow.Domain.Entities.Match", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("PlayerAwayId")
                        .HasColumnType("text");

                    b.Property<string>("PlayerHomeId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("PositionInRound")
                        .HasColumnType("integer");

                    b.Property<int>("RoundNumber")
                        .HasColumnType("integer");

                    b.Property<string>("TournamentId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PlayerAwayId");

                    b.HasIndex("PlayerHomeId");

                    b.HasIndex("TournamentId");

                    b.ToTable("Matches");
                });

            modelBuilder.Entity("GFlow.Domain.Entities.MatchEvent", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MatchId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Metadata")
                        .HasColumnType("text");

                    b.Property<int?>("MinuteOfPlay")
                        .HasColumnType("integer");

                    b.Property<string>("PlayerId")
                        .HasColumnType("text");

                    b.Property<string>("RecordedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("MatchId");

                    b.HasIndex("RecordedBy");

                    b.ToTable("MatchEvents");
                });

            modelBuilder.Entity("GFlow.Domain.Entities.Tournament", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<string>("City")
                        .HasColumnType("text");

                    b.Property<string>("CountryCode")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Emblem")
                        .HasColumnType("text");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GameCode")
                        .HasColumnType("text");

                    b.Property<string>("GameName")
                        .HasColumnType("text");

                    b.Property<double?>("Lat")
                        .HasColumnType("double precision");

                    b.Property<double?>("Lng")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("NumberOfRounds")
                        .HasColumnType("integer");

                    b.Property<string>("OrganizerId")
                        .HasColumnType("text");

                    b.Property<int>("PlayerLimit")
                        .HasColumnType("integer");

                    b.Property<int>("SeedingType")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("SystemType")
                        .HasColumnType("integer");

                    b.PrimitiveCollection<List<string>>("TieBreakers")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<long>("ViewCount")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("OrganizerId");

                    b.ToTable("Tournaments");
                });

            modelBuilder.Entity("GFlow.Domain.Entities.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("text");

                    b.Property<DateTime>("RefreshTokenExpiryTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("GFlow.Domain.Entities.UserActivity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ActivityType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TournamentId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("TournamentId");

                    b.HasIndex("UserId");

                    b.ToTable("UserActivities");
                });

            modelBuilder.Entity("GFlow.Domain.ValueObjects.TournamentParticipant", b =>
                {
                    b.Property<string>("TournamentId")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<bool>("HasReceivedBye")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsWithdrawn")
                        .HasColumnType("boolean");

                    b.Property<double>("Ranking")
                        .HasColumnType("double precision");

                    b.Property<double>("Score")
                        .HasColumnType("double precision");

                    b.HasKey("TournamentId", "UserId");

                    b.ToTable("TournamentParticipants");
                });

            modelBuilder.Entity("TournamentUser", b =>
                {
                    b.Property<string>("ParticipantsId")
                        .HasColumnType("text");

                    b.Property<string>("ParticipatedTournamentsId")
                        .HasColumnType("text");

                    b.HasKey("ParticipantsId", "ParticipatedTournamentsId");

                    b.HasIndex("ParticipatedTournamentsId");

                    b.ToTable("TournamentUser");
                });

            modelBuilder.Entity("TournamentUser1", b =>
                {
                    b.Property<string>("ModeratorsId")
                        .HasColumnType("text");

                    b.Property<string>("TournamentId")
                        .HasColumnType("text");

                    b.HasKey("ModeratorsId", "TournamentId");

                    b.HasIndex("TournamentId");

                    b.ToTable("TournamentModerators", (string)null);
                });

            modelBuilder.Entity("GFlow.Domain.Entities.Match", b =>
                {
                    b.HasOne("GFlow.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("PlayerAwayId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GFlow.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("PlayerHomeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GFlow.Domain.Entities.Tournament", null)
                        .WithMany()
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("GFlow.Domain.ValueObjects.MatchResult", "Result", b1 =>
                        {
                            b1.Property<string>("MatchId")
                                .HasColumnType("text");

                            b1.Property<string>("FinishType")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("FinishType");

                            b1.Property<double>("ScoreA")
                                .HasColumnType("double precision")
                                .HasColumnName("ScoreA");

                            b1.Property<double>("ScoreB")
                                .HasColumnType("double precision")
                                .HasColumnName("ScoreB");

                            b1.HasKey("MatchId");

                            b1.ToTable("Matches");

                            b1.WithOwner()
                                .HasForeignKey("MatchId");
                        });

                    b.Navigation("Result");
                });

            modelBuilder.Entity("GFlow.Domain.Entities.MatchEvent", b =>
                {
                    b.HasOne("GFlow.Domain.Entities.Match", null)
                        .WithMany("Events")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GFlow.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("RecordedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("GFlow.Domain.Entities.Tournament", b =>
                {
                    b.HasOne("GFlow.Domain.Entities.User", "Organizer")
                        .WithMany("OrganizedTournaments")
                        .HasForeignKey("OrganizerId");

                    b.Navigation("Organizer");
                });

            modelBuilder.Entity("GFlow.Domain.Entities.UserActivity", b =>
                {
                    b.HasOne("GFlow.Domain.Entities.Tournament", "Tournament")
                        .WithMany()
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GFlow.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tournament");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TournamentUser", b =>
                {
                    b.HasOne("GFlow.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("ParticipantsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GFlow.Domain.Entities.Tournament", null)
                        .WithMany()
                        .HasForeignKey("ParticipatedTournamentsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TournamentUser1", b =>
                {
                    b.HasOne("GFlow.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("ModeratorsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GFlow.Domain.Entities.Tournament", null)
                        .WithMany()
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GFlow.Domain.Entities.Match", b =>
                {
                    b.Navigation("Events");
                });

            modelBuilder.Entity("GFlow.Domain.Entities.User", b =>
                {
                    b.Navigation("OrganizedTournaments");
                });
#pragma warning restore 612, 618
        }
    }
}
